const MAIN_URL = 'http://10.0.2.2:3000';

const FAVOURITE_PRODUCT_BOX = 'FAVOURITE_PRODUCT_BOX';
const USER_INFO_BOX = 'USER_INFO_BOX';

const  PHONE_KEY = 'PHONE_KEY';
const  STREET_KEY = 'STREET_KEY';
const  CITY_KEY = 'CITY_KEY';
const  STATE_KEY = 'STATE_KEY';
const  POSTAL_CODE_KEY = 'POSTAL_CODE_KEY';
const  COUNTRY_KEY = 'COUNTRY_KEY';
